[package]
name = "cookcli"
version = "0.15.1"
edition = "2021"
description = "A command-line interface for managing and working with Cooklang recipes"
license = "MIT"
include = ["/src", "/Cargo.toml", "/Cargo.lock", "/README.md", "/templates", "/static"]

[[bin]]
name = "cook"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anstream = "0.6"
anstyle = "1"
anstyle-yansi = "2"
anyhow = "1"
askama = "0.12"
askama_axum = "0.4"
axum = { version = "0.7" }
camino = { version = "1", features = ["serde1"] }
clap = { version = "4.5", features = ["derive"] }
cooklang = { git = "https://github.com/cooklang/cooklang-rs.git", branch = "feat/bullets", default-features = false, features = ["aisle", "pantry"] }
cooklang-find = { version = "0.4.0" }
cooklang-import = "0.6.0"
cooklang-reports = { version = "0.2" }
directories = "6"
humantime = "2"
mime_guess = "2.0"
once_cell = "1"
open = "5.3"
openssl = { version = "0.10", features = ["vendored"] }
regex = "1"
rust-embed = "8"
scraper = "0.20"
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.9"
tabular = { version = "0.2", features = ["ansi-cell"] }
textwrap = { version = "0.16", features = ["terminal_size"] }
tokio = { version = "1", features = ["full"] }
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.5", features = ["fs", "trace", "cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
yansi = "1"
